parameters:
- name: RunOnnxRuntimeTests
  displayName: Run Tests?
  type: boolean
  default: true

- name: IsReleaseBuild
  displayName: Is a release build? Set it to true if you are doing an Onnx Runtime release.
  type: boolean
  default: false

- name: AdditionalBuildFlags
  displayName: Additional build flags for build.py
  type: string
  default: ''

- name: AdditionalWinBuildFlags
  displayName: Additional build flags that just for Windows Builds
  type: string
  default: ''

- name: OrtNugetPackageId
  displayName: Package name for nuget
  type: string
  default: 'Microsoft.ML.OnnxRuntime'

- name: BuildVariant
  type: string
  default: 'default'

- name: SpecificArtifact
  displayName: Use Specific Artifact
  type: boolean
  default: false

- name: BuildId
  displayName: Specific Artifact's BuildId
  type: string
  default: '0'

# Do not update this to a version that does not exist for the qnn-runtime Maven package:
# https://mvnrepository.com/artifact/com.qualcomm.qti/qnn-runtime
- name: QnnSDKVersion
  displayName: QNN SDK Version
  type: string
  default: 2.36.1.250708

- name: is1ES
  displayName: Is 1ES pipeline
  type: boolean
  default: false

stages:

- template: mac-cpu-packaging-pipeline.yml
  parameters:
    AllowReleasedOpsetOnly: 1
    BuildForAllArchs: true
    SpecificArtifact: ${{ parameters.SpecificArtifact }}
    BuildId: ${{ parameters.BuildId }}
    DoEsrp: true
