parameters:
- name: OS
  displayName: Opserating System
  type: string

- name: PoolName
  type: string

stages:
- stage: Final_Jar_Testing_${{parameters.OS}}
  dependsOn: []
  jobs:
  - job: Final_Jar_Testing_${{parameters.OS}}
    workspace:
      clean: all
    ${{ if eq(parameters.OS, 'MacOS') }}:
      pool:
        vmImage: 'macOS-15'
    ${{ if eq(parameters.OS, 'Linux') }}:
      pool:
        name: ${{ parameters.PoolName }}
    ${{ if eq(parameters.OS, 'Windows') }}:
      pool:
        name: ${{ parameters.PoolName }}
    variables:
    - name: runCodesignValidationInjection
      value: false
    timeoutInMinutes: 60
    steps:
    - template: set-version-number-variables-step.yml

    - bash: |
        echo "Downloading and installing Maven $(mavenVersion) for Linux..."
        MAVEN_DIR="$(Agent.TempDirectory)/apache-maven-$(mavenVersion)"
        # Download Maven binary
        wget https://archive.apache.org/dist/maven/maven-3/$(mavenVersion)/binaries/apache-maven-$(mavenVersion)-bin.tar.gz -O $(Agent.TempDirectory)/maven.tar.gz

        # Extract to the temp directory
        mkdir -p ${MAVEN_DIR}
        tar -xzf $(Agent.TempDirectory)/maven.tar.gz -C $(Agent.TempDirectory)

        # Add Maven's bin directory to the PATH for subsequent tasks in the job
        echo "##vso[task.prependpath]${MAVEN_DIR}/bin"
      displayName: 'Install Maven (Linux)'
      condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

    - pwsh: |
        echo "Downloading and installing Maven $(mavenVersion) for Windows..."
        $MAVEN_DIR = "$(Agent.TempDirectory)\apache-maven-$(mavenVersion)"
        # Download Maven binary
        Invoke-WebRequest -Uri "https://archive.apache.org/dist/maven/maven-3/$(mavenVersion)/binaries/apache-maven-$(mavenVersion)-bin.zip" -OutFile "$(Agent.TempDirectory)\maven.zip"

        # Extract to the temp directory
        Expand-Archive -Path "$(Agent.TempDirectory)\maven.zip" -DestinationPath "$(Agent.TempDirectory)"

        # Add Maven's bin directory to the PATH for subsequent tasks in the job
        echo "##vso[task.prependpath]$MAVEN_DIR\bin"
      displayName: 'Install Maven (Windows)'
      condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))


    - script: |
        echo "Maven is now on the PATH."
        mvn --version

    - download: build
      artifact: 'onnxruntime-java'
      displayName: 'Download Final Jar'

    - task: Maven@4
      displayName: 'Download Dependencies into App Folder'
      inputs:
        mavenPomFile: '$(Build.SourcesDirectory)/tools/ci_build/java/pom.xml'
        goals: 'dependency:copy-dependencies'
        options: '-DoutputDirectory=$(Pipeline.Workspace)/build/onnxruntime-java'
        publishJUnitTestResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        mavenVersionOption: 'Default'

    - task: PowerShell@2
      displayName: 'Run Java Tests on Windows'
      condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))
      inputs:
        targetType: 'inline'
        script: |
          $ErrorActionPreference = "Stop"
          cd $(Pipeline.Workspace)/build/onnxruntime-java

          $junitRunnerJar = Get-ChildItem -Path . -Filter "junit-platform-console-standalone-*.jar" -Recurse | Select-Object -First 1
          if ($null -eq $junitRunnerJar) {
            Write-Host "##vso[task.logissue type=error]JUnit Platform Console Standalone JAR not found!"
            exit 1
          }

          Write-Host "Running JUnit Tests..."
          & java -jar "$($junitRunnerJar.FullName)" `
            --scan-classpath . `
            --reports-dir "$($env:Build_ArtifactStagingDirectory)/TestResults"

    - task: Bash@3
      displayName: 'Run Java Tests on Linux/macOS'
      condition: and(succeeded(), in(variables['Agent.OS'], 'Linux', 'Darwin'))
      inputs:
        targetType: 'inline'
        script: |
          set -e
          cd $(Pipeline.Workspace)/build/onnxruntime-java

          # Set the correct library path based on the OS
          os_name=$(uname)
          if [[ "$os_name" == "Linux" ]]; then
            echo "Platform: Linux. Setting LD_LIBRARY_PATH."
            export LD_LIBRARY_PATH="$(pwd):$LD_LIBRARY_PATH"
          elif [[ "$os_name" == "Darwin" ]]; then
            echo "Platform: macOS. Setting DYLD_LIBRARY_PATH."
            export DYLD_LIBRARY_PATH="$(pwd):$DYLD_LIBRARY_PATH"
          fi

          JUNIT_RUNNER_JAR=$(find . -name "junit-platform-console-standalone-*.jar")
          if [[ -z "$JUNIT_RUNNER_JAR" ]]; then
            echo "##[error]JUnit Platform Console Standalone JAR not found!"
            exit 1
          fi

          echo "Running JUnit Tests..."
          java -jar "$JUNIT_RUNNER_JAR" \
            --scan-classpath . \
            --reports-dir "$(Build.ArtifactStagingDirectory)/TestResults"


    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '$(Build.ArtifactStagingDirectory)/TestResults/TEST-junit-jupiter.xml'
        failTaskOnFailedTests: true
